#!/usr/bin/env python
# -*- coding: utf-8 -*-
# EASY-INSTALL-ENTRY-SCRIPT: 'autoregkd','console_scripts'
__requires__ = "autoregkd"
import re
import sys

from autoregkd.__main__ import main

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw?|\.exe)?$", "", sys.argv[0])
    sys.exit(main())